// Secret-only augmentation. Cloudflare bindings and vars are generated by `wrangler types`.
interface Env {
  DATABASE_URL: string;
  NEON_AUTH_ISSUER: string;
  NEON_AUTH_JWKS_URL: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  REALTIMEKIT_APP_ID: string;
  CLOUDFLARE_REALTIMEKIT_APP_ID?: string;
  CLOUDFLARE_REALTIMEKIT_API_TOKEN: string;
  UPLOAD_SIGNING_SECRET: string;
  TELNYX_API_KEY?: string;
  TELNYX_FROM_NUMBER?: string;
}
